# Generated by Django 4.2.7 on 2023-12-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_developer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='residential_project',
            name='meta_description',
            field=models.CharField(default=set, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residential_project',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
