# Generated by Django 4.2.7 on 2023-12-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_commercial_project_residential_project_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial_project',
            name='propert_type',
            field=models.CharField(choices=[('Office Space', 'Office Space'), ('Shop/Showroom', 'Shop/Showroom'), ('Commercial Land', 'Commercial Land'), ('Warehouse/Godown', 'Warehouse/Godown'), ('Industrial Building', 'Industrial Building'), ('Industrial Shed', 'Industrial Shed')], max_length=25),
        ),
        migrations.AlterField(
            model_name='residential_project',
            name='propert_type',
            field=models.CharField(choices=[('Residential Land', 'Residential Land'), ('Residential Apartment', 'Residential Apartment'), ('Independent House/Villa', 'Independent House/Villa'), ('Studio Apartment', 'Studio Apartment'), ('Independent/Builder Floor', 'Independent/Builder Floor'), ('Serviced Apartments', 'Serviced Apartments'), ('Farm House', 'Farm House')], max_length=25),
        ),
    ]
