# Generated by Django 4.2.7 on 2023-12-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_cfacilities_cproject_images_cproject_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial_project',
            name='max_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercial_project',
            name='max_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commercial_project',
            name='min_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercial_project',
            name='min_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='residential_project',
            name='max_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residential_project',
            name='max_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='residential_project',
            name='min_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residential_project',
            name='min_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
