# Generated by Django 4.2.7 on 2023-12-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_commercial_project_max_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial_project',
            name='theme',
            field=models.CharField(choices=[('slider', 'slider'), ('Featured ', 'Featured'), ('Theme3', 'Theme3'), ('Theme4', 'Theme4'), ('Theme5', 'Theme5')], max_length=25),
        ),
        migrations.AlterField(
            model_name='residential_project',
            name='theme',
            field=models.CharField(choices=[('slider', 'slider'), ('Featured ', 'Featured'), ('Theme3', 'Theme3'), ('Theme4', 'Theme4'), ('Theme5', 'Theme5')], max_length=25),
        ),
    ]
