# Generated by Django 4.2.7 on 2023-12-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/img')),
                ('name', models.CharField(max_length=250, null=True)),
                ('line_1', models.CharField(max_length=250, null=True)),
                ('line_2', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
