# Generated by Django 4.2.7 on 2023-12-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='icon',
        ),
        migrations.AddField(
            model_name='amenities',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
